---
abstract: 'extends Module::Build to build/install/configure entire applications (i.e. web applications), not just modules and programs'
author:
  - 'Mattia Barbon <mbarbon@cpan.org>'
  - spadkins@gmail.com
build_requires:
  Module::Build: 0.28
  Test::Differences: 0.47
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Build
provides:
  App::Build:
    file: lib/App/Build.pm
    version: 0.74_01
requires:
  App::Options: 0
  File::Spec: 0
  Module::Build: 0.28
resources:
  license: http://dev.perl.org/licenses/
version: 0.74_01
