---
name: App-Build
version: 0.10
author:
  - stephen.adkins@officevision.com
abstract: a base/default class for building/installing applications
license: perl
requires:
  App::Options: 0
  File::Spec: 0
build_requires:
  Module::Build: 0
  Sysadm::Install: 0
provides:
  App::Build:
    file: lib/App/Build.pm
    version: 0.10
generated_by: Module::Build version 0.261
