---
name: App-Build
version: 0.62
author:
  - spadkins@gmail.com
abstract: 'extends Module::Build to build/install/configure entire applications (i.e. web applications), not just modules and programs'
license: perl
requires:
  App::Options: 0
  File::Spec: 0
  Module::Build: 0
build_requires:
  Module::Build: 0
provides:
  App::Build:
    file: lib/App/Build.pm
    version: 0.62
generated_by: Module::Build version 0.2611
