---
name: App-Build
version: 0.61
author:
  - stephen.adkins@officevision.com
abstract: ~
license: perl
requires:
  App::Options: 0
  File::Spec: 0
  Module::Build: 0
build_requires:
  Module::Build: 0
provides:
  App::Build:
    file: lib/App/Build.pm
    version: 0.61
generated_by: Module::Build version 0.2611
