---
name: App-Build
version: 0.64
author:
  - 'Mattia Barbon <mbarbon@cpan.org>'
  - spadkins@gmail.com
abstract: 'extends Module::Build to build/install/configure entire applications (i.e. web applications), not just modules and programs'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  App::Options: 0
  File::Spec: 0
  Module::Build: 0
build_requires:
  Module::Build: 0.19
provides:
  App::Build:
    file: lib/App/Build.pm
    version: 0.64
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
